name: parakeet-genai-stack

# Embeddings generation only:
# docker compose -f compose.yml --profile generation up --build

# Embeddings generation then start the application:
# docker compose -f compose.yml --profile generation --profile application up --build 

# Start the application only:
# docker compose -f compose.yml --profile application up --build 

services:

  elasticsearch:
    profiles: [generation, application]
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xmx8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
      retries: 300
      interval: 1s

  elasticsearch_settings:
    profiles: [generation, application]
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch_settings
    restart: 'no'
    command: >
      bash -c '        
        echo "Setup the kibana_system password";
        until curl -s -u "elastic:${ELASTIC_PASSWORD}" -X POST http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${ELASTIC_PASSWORD}\"}" -H "Content-Type: application/json" | grep -q "^{}"; do sleep 5; done;
      '

  kibana:
    profiles: [generation, application]
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    depends_on:
      elasticsearch_settings:
        condition: service_completed_successfully
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q 'All services are available'"]
      retries: 300
      interval: 1s

  download-local-llm-embeddings:
    profiles: [generation, application]
    image: curlimages/curl:8.12.1
    entrypoint:
      - "sh"
      - "-c"
      - 'curl "${OLLAMA_BASE_URL}/api/pull" -d "{\"name\": \"${LLM_EMBEDDINGS}\"}"'
    extra_hosts:
        - "host.docker.internal:host-gateway"

  create-embeddings:
    profiles: [generation]
    build:
      context: ./create-embeddings
      dockerfile: Dockerfile    
    environment:
      - CONTENT_PATH=/app/data # into the container
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_EMBEDDINGS=${LLM_EMBEDDINGS}
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_INDEX=${ELASTIC_INDEX}
    volumes:
      - ${OBSIDIAN_VAULT_PATH}:/app/data
    depends_on:
      download-local-llm-embeddings:
        condition: service_completed_successfully
      kibana:
        condition: service_started
      elasticsearch:
        condition: service_started
    extra_hosts:
        - "host.docker.internal:host-gateway"

  download-local-llm:
    profiles: [application]
    image: curlimages/curl:8.12.1
    entrypoint:
      - "sh"
      - "-c"
      - 'curl "${OLLAMA_BASE_URL}/api/pull" -d "{\"name\": \"${LLM_CHAT}\"}"'
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend:
    profiles: [application]
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_CHAT=${LLM_CHAT}
      - LLM_EMBEDDINGS=${LLM_EMBEDDINGS}
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_INDEX=${ELASTIC_INDEX}
      - MAX_SIMILARITIES=${MAX_SIMILARITIES}
      - HISTORY_MESSAGES=${HISTORY_MESSAGES}
      - OPTION_TEMPERATURE=${OPTION_TEMPERATURE}
      - OPTION_REPEAT_LAST_N=${OPTION_REPEAT_LAST_N}
      - OPTION_REPEAT_PENALTY=${OPTION_REPEAT_PENALTY}
      - OPTION_TOP_P=${OPTION_TOP_P}
      - OPTION_TOP_K=${OPTION_TOP_K}
      - OPTION_NUM_CTX=${OPTION_NUM_CTX}
      - SYSTEM_INSTRUCTIONS_PATH=${SYSTEM_INSTRUCTIONS_PATH}

    volumes:
      - ./instructions:/app/instructions
    depends_on:
      download-local-llm-embeddings:
        condition: service_completed_successfully
      download-local-llm:
        condition: service_completed_successfully
      kibana:
        condition: service_started
      elasticsearch:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./backend/main.go
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  frontend:
    profiles: [application]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 9090:8501
    environment:
      - BACKEND_SERVICE_URL=http://backend:5050
      - PAGE_TITLE=🤓 AMA about my Obsidian 🔮!
      - PAGE_HEADER=Made with 💖 and probably too much caffeine
      - PAGE_ICON=🤖
      - LLM_CHAT=${LLM_CHAT}
      - LLM_EMBEDDINGS=${LLM_EMBEDDINGS}
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/app.py

